### ISSUE TITLE
Issues noted by team walk-through

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-1-course#15]
Put your issues here!

**Comment by lindsayplatt** [comment]
From @collnell 

> I think there's an error in issue #2 - says 
> ```
> git clone git@github.com:collnell/ds-pipelines-targets-1.git
> cd ds-pipelines-1
> ```
>
> should be `cd ds-pipelines-targets-1`

**Comment by lindsayplatt** [comment]
From @ellenbechtel 

> Typo in Issue #1: Now, verify that **your the number** you just commented is greater than or equal to 0.3.1.

**Comment by jsadler2** [comment]
The link in the Teams message thread did not work (https://lab.github.com/USGS-R/intro-to-targets-pipelines/10.1.0)

This link did work: https://lab.github.com/USGS-R/intro-to-targets-pipelines/main

**Comment by lindsayplatt** [comment]
Add a comment about not committing `out/` folders in or prior to the PR activity at https://github.com/USGS-R/ds-pipelines-targets-1-course/blob/main/responses/10a-folders-acvitity.md

**Comment by jread-usgs** [comment]
Also, is it a typo to say "(you are welcome to watch the full main talk from 7:20 to 7:40)" since the whole talk is a lot longer than 20s?

**Comment by jread-usgs** [comment]
I think we need to make it clear in [this comment](https://github.com/jread-usgs/ds-pipelines-targets-1/pull/7#issuecomment-867163372) that we're expecting the trainees to use the phase folders and structure from the prior PR. It is a bit too subtle in the current instructions.

**Comment by jread-usgs** [comment]
for 
> now try making a change to the template_1 variable in your function that creates the .txt file

it doesn't seem like the instructor pipeline is building the templated .txt file per 
![image](https://user-images.githubusercontent.com/2349007/123170684-6ad0db00-d440-11eb-9ceb-b68bab51b055.png)

Should we just get rid of that part of the original script?

**Comment by jread-usgs** [comment]
`tidyverse` is used [here](https://github.com/USGS-R/ds-pipelines-targets-1-course/blob/a4708ec4c2de75ac63f785b52baefdf1c5e343cb/responses/30-makefile-anatomy.md) but isn't in the initial set of packages to install (listed [here](https://github.com/USGS-R/ds-pipelines-targets-1-course/blob/965bb59bd9ea826e7d40e1666d4ec956eea09990/responses/01-install-activity.md) )
Seems that package should be there too? (it also pops up in targets-2)

**Comment by lindsayplatt** [comment]
a note about the diagnostic txt file - it should still be in there and was just a mistake in that image. Switched to:

![image](https://user-images.githubusercontent.com/13220910/128781588-64911332-6464-4cb3-b77d-eaa7063d6bc1.png)
