### ISSUE TITLE
need a different template repo?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-1-course#2]
The template repo doesn't start with anything `targets` or `scipiper` specific, do we really need to change?

https://github.com/USGS-R/ds-pipelines-1-template

**Comment by lindsayplatt** [comment]
The answer is yes because it clones the repo and if you have already taken the scipiper version, it fails instantly because it can't make another repo under your account with the same name.

**Comment by lindsayplatt** [comment]
Here's the new template repo! https://github.com/USGS-R/ds-pipelines-targets-1-template

**Comment by lindsayplatt** [comment]
That fixed the issue and I can not start the course

**Comment by aappling-usgs** [comment]
I remember doing a lot of manual syncs with this interface. Too bad they haven't fixed it a year later, but at least there's a workaround.
