### ISSUE TITLE
Ensure users are working off a fork of the pipelines training 

### ISSUE THREAD

**Issue by msleckman** [USGS-R/ds-pipelines-targets-1-course#28]
Currently there is no instructions on forking this training repository, which may lead to many users pushing specific branches to  this repo.  
https://github.com/DOI-USGS/ds-pipelines-targets-1-course/blob/79db75d30afa03eda90aae2c7c472bd6bb5dbeba/course-instructions.md?plain=1#L51-L53

@padilla410 just checking, was there a reason for this? Are training participants suppose to clone directly and have this repo be the `origin` repo? 
 
I'd suggest adding forking instructions to the `course-instructions.md` and ensure that participants can work off their forks.

**Comment by jpadilla-usgs** [comment]
Nice catch! I'll tackle on Friday

Right now this repo is a template so I think users should copy the template to their accounts and then use branches to update things. @aaarcher-usgs any thoughts here?

**Comment by msleckman** [comment]
Copy is different from fork in that case? 
I like that it can be copy and turn into a repo in the user's own github profile. I'd favor doing that versus forks.

**Comment by jpadilla-usgs** [comment]
Margaux and I discussed this topic on a teams call - we are going to keep the directions in the readme
