### ISSUE TITLE
link still broken?

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/ds-pipelines-targets-1-course#5]
I think https://github.com/USGS-R/ds-pipelines-1-course/issues/61 is still an issue in this repo (see https://github.com/USGS-R/ds-pipelines-targets-1-course/blob/main/responses/10-structure.md). Not sure why `repoURL` is only returning `https://github.com/` but perhaps we need to use a different template variable? See https://lab.github.com/docs/writing-responses

**Comment by jzwart** [comment]
I think it might be a `main` vs. `master` branch difference? I changed the url with #8

**Comment by lindsayplatt** [comment]
Hmmm that is a good idea, but I think it is how the Learning Lab  templating is not correctly working.  Even if I change `master` to `main` in the link to `my_happy_script.R` in [your issue](https://github.com/jzwart/ds-pipelines-targets-1/issues/3), it still can't find it because it is missing `jzwart/ds-pipelines-1`

**Comment by jzwart** [comment]
hm. 
Maybe it's `repoUrl` and not `repoURL`. Not sure if the capitalization matters but the writing responses have the `r` and `l` as lowercase, not uppercase

**Comment by lindsayplatt** [comment]
OH MY GOODNESS! I bet that is it ... I see `{{ repoUrl }}` used in the docs https://lab.github.com/docs/using-actions#passing-data-into-responses

**Comment by lindsayplatt** [comment]
Attempted to fix in https://github.com/USGS-R/ds-pipelines-targets-1-course/commit/f4c71e1a501d124f88e2e28eaf8baf8b115b08ec, we shall see if that does it 🤞

**Comment by lindsayplatt** [comment]
Hmmm Simon's should have been fixed but it doesn't look like that worked :( https://github.com/SimonTopp/ds-pipelines-targets-1/issues/3#issue-895353526

**Comment by jzwart** [comment]
strange. The syntax looks exactly like they're suggesting in the docs...

**Comment by lindsayplatt** [comment]
Hmmm OK so it might be because it doesn't actually look like it updated in the repo (https://github.com/USGS-R/ds-pipelines-targets-1-course/blob/965bb59bd9ea826e7d40e1666d4ec956eea09990/responses/10-structure.md). Might be one of those github learning lab edit vs repo commit issues. Trying again.

**Comment by lindsayplatt** [comment]
Though, my branch is up to date and when I do a PR, it doesn't show anything to compare. UGH!

**Comment by lindsayplatt** [comment]
Huzzah! Adding a space to force the update worked. Now, I am going to test.

**Comment by lindsayplatt** [comment]
Alrighty, that change worked when I just tested the course out by taking it myself. Closing this now :)
